title: Craig Allen
author: Craig Allen
email: craig@openwavesdesign.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Frontend web development blog.

# social links
twitter_username: craigger # DO NOT include the @ character, or else the build will fail!
github_username:  craigallen # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
